version: '3'

services:
  rsyslog:
    image: robbert229/rsyslog
    restart: always
    ports:
      - "514:514"
      - "514:514/udp"
    volumes:
      - docker-rsyslog-storage:/var/log

volumes:
  docker-rsyslog-storage:
