version: '3'

services:
  rsyslog:
    image: robbert229/rsyslog
    ports:
      - "514:514"
      - "514:514/udp"
    volumes:
      - docker-rsyslog-storage:/var/log
      - ./rsyslog/logrotate.conf:/etc/logrotate.d/rsyslog:ro

volumes:
  docker-rsyslog-storage:
